[[github_section]]
items = [
  ["profile", "https://github.com/{user}"],
  ["|"],
  ["organisation", "https://github.com/{organisation}"],
  ["|"],
  ["Repos", "https://github.com/{user}?tab=repositories"],
  ["Pull Requests", "https://github.com/pulls/inbox"],
]

[[search_bar]]
action = "https://www.google.com/search"
placeholder = "Search (googoo)"
autocomplete = "off"

[[card_section]]
title = "Card Section"
items = [
  ["label", "https://example.com"],
  ["label", "https://example.com"],
]
